# Generated by Django 3.2.5 on 2021-08-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fiscal', models.CharField(max_length=36)),
                ('matricula_fiscal', models.CharField(max_length=5)),
                ('nivel', models.CharField(choices=[('FISCAL SANITÁRIO I', 'FISCAL SANITÁRIO I'), ('FISCAL SANITÁRIO II', 'FISCAL SANITÁRIO II')], max_length=19)),
                ('primeiro_nome', models.CharField(max_length=16)),
            ],
        ),
    ]
