# Generated by Django 3.2.5 on 2021-08-01 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proprietario', models.CharField(max_length=55)),
                ('logradouro_proprietario', models.CharField(max_length=60)),
                ('numero_proprietario', models.CharField(max_length=10)),
                ('complemento_proprietario', models.CharField(max_length=30, null=True)),
                ('bairro_proprietario', models.CharField(max_length=30)),
                ('cep_proprietario', models.CharField(max_length=9)),
                ('municipio_proprietario', models.CharField(max_length=60)),
                ('estado_proprietario', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao_terreno', models.CharField(max_length=18, verbose_name='Inscrição imobiliária do terreno')),
                ('logradouro_terreno', models.CharField(max_length=60, verbose_name='Logradouro do terreno')),
                ('numero_terreno', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro_terreno', models.CharField(max_length=30, verbose_name='Bairro')),
                ('cep_terreno', models.CharField(choices=[('37950-000', '37950-000')], max_length=9, verbose_name='CEP')),
                ('municipio_terreno', models.CharField(choices=[('SÃO SEBASTIÃO DO PARAÍSO', 'SÃO SEBASTIÃO DO PARAÍSO')], max_length=60, verbose_name='Cidade')),
                ('estado_terreno', models.CharField(choices=[('MINAS GERAIS', 'MINAS GERAIS')], max_length=30, verbose_name='Estado')),
                ('lote_terreno', models.CharField(max_length=4)),
                ('quadra_terreno', models.CharField(max_length=4)),
                ('area_terreno', models.FloatField()),
                ('logradouro_correspondencia', models.CharField(max_length=60, verbose_name='Logradouro de correspondência')),
                ('numero_correspondencia', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento_correspondencia', models.CharField(max_length=30, null=True, verbose_name='Complemento')),
                ('bairro_correspondencia', models.CharField(max_length=30, verbose_name='Bairro')),
                ('cep_correspondencia', models.CharField(max_length=9, verbose_name='CEP')),
                ('municipio_correspondencia', models.CharField(max_length=60, verbose_name='Cidade')),
                ('estado_correspondencia', models.CharField(max_length=30, verbose_name='Estado')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrenos.proprietario')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=12)),
                ('solicitante_protocolo', models.CharField(choices=[('PESSOA FÍSICA', 'PESSOA FÍSICA'), ('CORPO DE BOMBEIROS', 'CORPO DE BOMBEIROS'), ('VEREADORES', 'VEREADORES'), ('MINISTÉRIO PÚBLICO', 'MINISTÉRIO PÚBLICO'), ('ORDEM JUDICIAL', 'ORDEM JUDICIAL'), ('OUTRAS INSTITUIÇÕES', 'OUTRAS INSTITUIÇÕES')], max_length=40)),
                ('logradouro_protocolo', models.CharField(max_length=60)),
                ('bairro_protocolo', models.CharField(max_length=60)),
                ('descricao_protocolo', models.CharField(max_length=250)),
                ('status_protocolo', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('NOTIFICADO', 'NOTIFICADO'), ('AUTUADO', 'AUTUADO'), ('DEFESA', 'DEFESA'), ('ENCERRADO', 'ENCERRADO')], max_length=15)),
                ('entrada_protocolo', models.DateField()),
                ('encerramento_protocolo', models.DateField(null=True)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrenos.fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_notificacao', models.DateField()),
                ('data_inspecao', models.DateField()),
                ('horario_inspecao', models.TimeField()),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrenos.fiscal')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrenos.protocolo')),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrenos.terreno')),
            ],
        ),
    ]
