# Generated by Django 3.2.5 on 2021-08-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0005_alter_notificacao_rastreio_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='cumpriu_notificacao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_entrega_notificacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_retorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='horario_retorno',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='observacoes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='rastreio_notificacao',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
