# Generated by Django 3.2.5 on 2021-08-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0006_auto_20210806_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='cumpriu_notificacao',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SIM', 'SIM'), ('NÃO', 'NÃO')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
