# Generated by Django 3.2.5 on 2021-08-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0009_auto_20210814_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracao',
            name='data_inspecao_2',
            field=models.DateField(verbose_name='Data da nova inspeção'),
        ),
    ]
