# Generated by Django 3.2.5 on 2021-08-18 02:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0010_alter_infracao_data_inspecao_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
            ],
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='encerramento_protocolo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
