# Generated by Django 3.2.5 on 2021-08-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0016_alter_inspecao_foto_inspecao_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecao',
            name='foto_inspecao_1',
            field=models.ImageField(default='images/profile/avatar-default-icon.png', upload_to='media'),
        ),
    ]
