# Generated by Django 3.2.5 on 2021-08-23 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0021_alter_inspecao_foto_inspecao_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspecao',
            name='fiscal',
        ),
        migrations.RemoveField(
            model_name='inspecao',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='inspecao',
            name='terreno',
        ),
        migrations.AddField(
            model_name='inspecao',
            name='data_relatorio',
            field=models.DateField("2021-01-05"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspecao',
            name='notificacao',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='terrenos.notificacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='foto_inspecao_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
